name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0 
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Library_Api/Library_Api.csproj
      - name: Build
        run: dotnet build --no-restore Library_Api/Library_Api.csproj
      - name: Test
        run: dotnet test Library_Api.Test/Library_Api.Test.csproj
